
CREATE TABLE data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  puid CHAR(36),
  servicename VARCHAR(100),
  username VARCHAR(100),
  passkey VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
